Implement clamshell functionality for sway
regolith-linux/regolith-wm-config pull request #15
Opened 2023-11-04 15:45 UTC by SoumyaRanjanPatnaik

2023-11-05 04:26 UTC, kgilmer requested changes
Nice!  Subsequent to this change, we'll also want to document the available setting enums in https://github.com/regolith-linux/regolith-desktop-website/pull/38 and https://github.com/regolith-linux/regolith-desktop-website/blob/main/content/docs/reference/xresources.md.

2023-11-05 04:26 UTC, kgilmer commented on scripts/regolith-sway-clamshell
> +ACTION=$( trawlcat regolith.clamshell.action "DISABLE_OUTPUT" )
Given that this key controls window manager behavior, a key name prefix of `wm.` may be more consistent.

2023-11-07 14:54 UTC, kgilmer approved these changes

2023-11-07 14:54 UTC, merged

2023-11-07 15:50 UTC, SoumyaRanjanPatnaik commented
@kgilmer can you test if this works on your setup. Also should we make this a required dependency?